apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: master-api
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.PublicHostname | quote }}
  rules:
  - host: {{ .Values.PublicHostname | quote }}
    http:
      paths:
      - backend:
          serviceName: master-api
          servicePort: 443
