[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "~19.0.0"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "~10.14.0"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "17.0.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-test/deep"
  version = "1.0.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~7.0.0"

[[constraint]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.10.0"

[prune]
  go-tests = true
  unused-packages = true
