[[constraint]]
  name = "github.com/openshift/installer"
  version = "0.16.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.4"

[prune]
  go-tests = true
  unused-packages = true
