
[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "12.1.0"

[[constraint]]
  name = "github.com/openshift/installer"
  # We use HEAD. For the release this should be pointed to release
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.4"

[prune]
  go-tests = true
  unused-packages = true
