apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "master-data"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "managed-premium"

