# intervalNanoseconds: 10000000000 # every 10 seconds
prometheusEndpoint: https://prometheus-k8s.openshift-monitoring.svc:9091/
statsdSocket: mdm_statsd.socket # nc -U -l mdm_statsd.socket
queries:
- query: 'ALERTS'
- query: 'sum(apiserver_request_count) without (client, code, contentType, endpoint, job, namespace, resource, scope, service, subresource, verb)'
  name: apiserver_request_count
- query: 'sum(apiserver_request_latencies_bucket) without (endpoint, job, namespace, resource, scope, service, subresource, verb)'
  name: apiserver_request_latencies_bucket
- query: 'sum(apiserver_request_latencies_sum) without (endpoint, job, namespace, resource, scope, service, subresource, verb)'
  name: apiserver_request_latencies_sum
- query: 'cloudprovider_azure_api_request_duration_seconds_bucket{le=~"1|5|10|\\+Inf"}'
- query: 'cloudprovider_azure_api_request_duration_seconds_count'
- query: 'cloudprovider_azure_api_request_duration_seconds_sum'
- query: 'container_cpu_system_seconds_total{namespace=~"default|openshift|openshift-.+|kube-.+|", container_name!="", container_name!="POD"}'
- query: 'container_cpu_user_seconds_total{namespace=~"default|openshift|openshift-.+|kube-.+|", container_name!="", container_name!="POD"}'
- query: 'container_fs_limit_bytes{namespace=~"default|openshift|openshift-.+|kube-.+|", container_name!="", container_name!="POD"}'
- query: 'container_fs_sector_reads_total{namespace=~"default|openshift|openshift-.+|kube-.+|", container_name!="", container_name!="POD"} != 0'
- query: 'container_fs_sector_writes_total{namespace=~"default|openshift|openshift-.+|kube-.+|", container_name!="", container_name!="POD"} != 0'
- query: 'container_fs_usage_bytes{namespace=~"default|openshift|openshift-.+|kube-.+|", container_name!="", container_name!="POD"}'
- query: 'container_memory_cache{namespace=~"default|openshift|openshift-.+|kube-.+|", container_name!="", container_name!="POD"}'
- query: 'container_memory_failcnt{namespace=~"default|openshift|openshift-.+|kube-.+|", container_name!="", container_name!="POD"} != 0'
- query: 'container_memory_rss{namespace=~"default|openshift|openshift-.+|kube-.+|", container_name!="", container_name!="POD"}'
- query: 'container_spec_memory_limit_bytes{namespace=~"default|openshift|openshift-.+|kube-.+|", container_name!="", container_name!="POD"}'
- query: 'container_start_time_seconds{namespace=~"default|openshift|openshift-.+|kube-.+|", container_name!="", container_name!="POD"}'
- query: 'kube_cronjob_next_schedule_time{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_cronjob_status_last_schedule_time{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_daemonset_status_current_number_scheduled{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_daemonset_status_desired_number_scheduled{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_daemonset_status_number_available{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_daemonset_status_number_misscheduled{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_daemonset_status_number_ready{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_daemonset_status_number_unavailable{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_daemonset_updated_number_scheduled{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_deployment_status_replicas_available{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_deployment_status_replicas_unavailable{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_deployment_status_replicas_updated{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_deployment_status_replicas{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_endpoint_address_available{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_endpoint_address_not_ready{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_job_complete{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_job_status_active{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_job_status_completion_time{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_job_status_failed{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_job_status_start_time{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_job_status_succeeded{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_node_info'
- query: 'kube_node_spec_unschedulable != 0'
- query: 'kube_node_status_allocatable_cpu_cores'
- query: 'kube_node_status_allocatable_memory_bytes'
- query: 'kube_node_status_allocatable_pods'
- query: 'kube_node_status_capacity_cpu_cores'
- query: 'kube_node_status_capacity_memory_bytes'
- query: 'kube_node_status_capacity_pods'
- query: 'kube_node_status_condition != 0'
- query: 'kube_persistentvolume_status_phase{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_persistentvolumeclaim_status_phase{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_pod_completion_time{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_pod_container_info{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_pod_container_resource_limits_cpu_cores{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_pod_container_resource_limits_memory_bytes{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_pod_container_resource_requests_cpu_cores{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_pod_container_resource_requests_memory_bytes{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_pod_container_status_ready{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_pod_container_status_restarts_total{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_pod_container_status_running{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_pod_container_status_terminated_reason{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_pod_container_status_terminated{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_pod_container_status_waiting_reason{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_pod_container_status_waiting{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_pod_created{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_pod_info{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_pod_labels{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_pod_owner{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_pod_spec_volumes_persistentvolumeclaims_readonly{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_pod_start_time{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_pod_status_phase{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_pod_status_ready{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_pod_status_scheduled{namespace=~"default|openshift|openshift-.+|kube-.+|"} != 0'
- query: 'kube_replicaset_status_fully_labeled_replicas{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_replicaset_status_ready_replicas{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_replicaset_status_replicas{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_statefulset_status_replicas_current{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_statefulset_status_replicas_ready{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_statefulset_status_replicas_updated{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kube_statefulset_status_replicas{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'kubelet_docker_operations_errors'
- query: 'kubelet_runtime_operations_errors'
- query: 'node_boot_time_seconds'
- query: 'node_cpu_seconds_total'
- query: 'node_disk_read_bytes_total'
- query: 'node_disk_written_bytes_total'
- query: 'node_filesystem_device_error != 0'
- query: 'node_filesystem_free_bytes'
- query: 'node_filesystem_readonly != 0'
- query: 'node_filesystem_size_bytes'
- query: 'node_load1'
- query: 'node_load15'
- query: 'node_load5'
- query: 'node_memory_Active_anon_bytes'
- query: 'node_memory_Active_bytes'
- query: 'node_memory_Active_file_bytes'
- query: 'node_memory_AnonHugePages_bytes'
- query: 'node_memory_AnonPages_bytes'
- query: 'node_memory_Bounce_bytes'
- query: 'node_memory_Buffers_bytes'
- query: 'node_memory_Cached_bytes'
- query: 'node_memory_CmaFree_bytes'
- query: 'node_memory_CmaTotal_bytes'
- query: 'node_memory_CommitLimit_bytes'
- query: 'node_memory_Committed_AS_bytes'
- query: 'node_memory_DirectMap1G_bytes'
- query: 'node_memory_DirectMap2M_bytes'
- query: 'node_memory_DirectMap4k_bytes'
- query: 'node_memory_Dirty_bytes'
- query: 'node_memory_HardwareCorrupted_bytes'
- query: 'node_memory_HugePages_Free'
- query: 'node_memory_HugePages_Rsvd'
- query: 'node_memory_HugePages_Surp'
- query: 'node_memory_HugePages_Total'
- query: 'node_memory_Hugepagesize_bytes'
- query: 'node_memory_Inactive_anon_bytes'
- query: 'node_memory_Inactive_bytes'
- query: 'node_memory_Inactive_file_bytes'
- query: 'node_memory_KernelStack_bytes'
- query: 'node_memory_Mapped_bytes'
- query: 'node_memory_MemAvailable_bytes'
- query: 'node_memory_MemFree_bytes'
- query: 'node_memory_MemTotal_bytes'
- query: 'node_memory_Mlocked_bytes'
- query: 'node_memory_NFS_Unstable_bytes'
- query: 'node_memory_PageTables_bytes'
- query: 'node_memory_Shmem_bytes'
- query: 'node_memory_Slab_bytes'
- query: 'node_memory_SReclaimable_bytes'
- query: 'node_memory_SUnreclaim_bytes'
- query: 'node_memory_SwapCached_bytes'
- query: 'node_memory_SwapFree_bytes'
- query: 'node_memory_SwapTotal_bytes'
- query: 'node_memory_Unevictable_bytes'
- query: 'node_memory_VmallocChunk_bytes'
- query: 'node_memory_VmallocTotal_bytes'
- query: 'node_memory_VmallocUsed_bytes'
- query: 'node_memory_Writeback_bytes'
- query: 'node_memory_WritebackTmp_bytes'
- query: 'node_network_receive_bytes_total != 0'
- query: 'node_network_receive_drop_total != 0'
- query: 'node_network_receive_errs_total != 0'
- query: 'node_network_receive_packets_total != 0'
- query: 'node_network_transmit_bytes_total != 0'
- query: 'node_network_transmit_drop_total != 0'
- query: 'node_network_transmit_errs_total != 0'
- query: 'node_network_transmit_packets_total != 0'
- query: 'node_uname_info'
- query: 'process_cpu_seconds_total{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'process_max_fds{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'process_open_fds{namespace=~"default|openshift|openshift-.+|kube-.+|"}'
- query: 'storage_operation_duration_seconds_bucket{namespace=~"default|openshift|openshift-.+|kube-.+|", volume_plugin="kubernetes.io/azure-disk"}'
- query: 'storage_operation_duration_seconds_count{namespace=~"default|openshift|openshift-.+|kube-.+|", volume_plugin="kubernetes.io/azure-disk"}'
- query: 'storage_operation_duration_seconds_sum{namespace=~"default|openshift|openshift-.+|kube-.+|", volume_plugin="kubernetes.io/azure-disk"}'
- query: 'storage_operation_errors_total{namespace=~"default|openshift|openshift-.+|kube-.+|", volume_plugin="kubernetes.io/azure-disk"}'
- query: 'up'
# account: RPOpenShift
# namespace: Prometheus
# region: eastus
# subscriptionId: 95a188ab-74f7-4d5e-829b-18179a23ff93
# resourceGroupName: resourcegroup

## for testing outside of the cluster:
# prometheusEndpoint: https://prometheus-k8s-openshift-monitoring.$PUBLIC_SUBDOMAIN.osadev.cloud/
# token: $(oc serviceaccounts get-token -n openshift-monitoring prometheus-k8s) # eyJh...
# insecureSkipVerify: true
