intervalNanoseconds: 60000000000 # every minute
prometheusFederateEndpoint: https://prometheus-k8s.openshift-monitoring.svc:9091/federate
statsdEndpoint: localhost:8051
series:
- kube_node_info
- kube_node_status_allocatable_cpu_cores
- kube_node_status_allocatable_memory_bytes
- kube_node_status_condition
- kube_pod_container_status_restarts_total
- kube_pod_info
- kube_pod_status_phase
- kube_pod_status_ready
namespace: Prometheus
region: eastus

## for testing outside of the cluster:
# intervalNanoseconds: 10000000000 # every 10s
# prometheusFederateEndpoint: https://prometheus-k8s-openshift-monitoring.$RESOURCEGROUP.osadev.cloud/federate
# token: eyJh...
# insecureSkipVerify: true
