# intervalNanoseconds: 10000000000 # every 10 seconds
prometheusFederateEndpoint: https://prometheus-k8s.openshift-monitoring.svc:9091/federate
statsdSocket: mdm_statsd.socket # nc -U -l mdm_statsd.socket
series:
- kube_node_info
- kube_node_status_allocatable_cpu_cores
- kube_node_status_allocatable_memory_bytes
- kube_node_status_condition
- kube_pod_container_status_restarts_total
- kube_pod_info
- kube_pod_status_phase
- kube_pod_status_ready
# account: RPOpenShift
# namespace: Prometheus
# region: eastus
# subscriptionId: 95a188ab-74f7-4d5e-829b-18179a23ff93
# resourceGroupName: resourcegroup

## for testing outside of the cluster:
# prometheusFederateEndpoint: https://prometheus-k8s-openshift-monitoring.$RESOURCEGROUP.osadev.cloud/federate
# token: $(oc serviceaccounts get-token -n openshift-monitoring prometheus-k8s) # eyJh...
# insecureSkipVerify: true
