apiVersion: v1
kind: Service
metadata:
  name: master-api
spec:
  selector:
    openshift.io/component: api
  ports:
  - name: apiserver
    port: 443
  - name: tunnel
    port: 444
  type: LoadBalancer
