{{if 0}}
apiVersion: v1
kind: Secret
metadata:
  name: admin-kubeconfig
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
data:
  admin.kubeconfig: {{ .Values.AdminKubeconfig }}
{{end}}
