apiVersion: v1
kind: Secret
metadata:
  name: etc-origin-cloudprovider
stringData:
  azure.conf: |
    tenantId: {{ .Values.TenantID }}
    subscriptionId: {{ .Values.SubscriptionID }}
    aadClientId: {{ .Values.ClientID }}
    aadClientSecret: {{ .Values.ClientSecret }}
    aadTenantId: {{ .Values.TenantID }}
    resourceGroup: {{ .Values.ResourceGroup }}
    location: {{ .Values.Location }}
    securityGroupName: nsg-compute
    primaryAvailabilitySetName: as-compute
