apiVersion: v1
kind: Secret
metadata:
  name: etcd-client-tls
data:
  etcd-client-ca.crt: {{ .Values.EtcdCaCert | quote }}
  etcd-client.crt: {{ .Values.EtcdClientCert | quote }}
  etcd-client.key: {{ .Values.EtcdClientKey | quote }}
