apiVersion: v1
kind: Secret
metadata:
  name: etcd-peer-tls
data:
  peer-ca.crt: {{ .Values.EtcdCaCert | quote }}
  peer.crt: {{ .Values.EtcdPeerCert | quote }}
  peer.key: {{ .Values.EtcdPeerKey | quote }}
