apiVersion: v1
kind: Secret
metadata:
  name: etcd-server-tls
data:
  server-ca.crt: {{ .Values.EtcdCaCert | quote }}
  server.crt: {{ .Values.EtcdServerCert | quote }}
  server.key: {{ .Values.EtcdServerKey | quote }}
