apiVersion: v1
kind: Secret
metadata:
  name: servicecatalog-api
data:
  etcd-ca.crt: {{ .Values.EtcdCaCert }}
  etcd-client.crt: {{ .Values.EtcdClientCert }}
  etcd-client.key: {{ .Values.EtcdClientKey }}
  apiserver.crt: {{ .Values.ServiceCatalogServerCert }}
  apiserver.key: {{ .Values.ServiceCatalogServerKey }}
