apiVersion: v1
kind: Secret
metadata:
  name: sync
stringData:
  config.yaml: |
    AlertManagerProxySessionSecret: {{ .Values.AlertManagerProxySessionSecret | quote }}
    AlertsProxySessionSecret: {{ .Values.AlertsProxySessionSecret | quote }}
    AnsibleServiceBrokerImage: {{ .Values.AnsibleServiceBrokerImage | quote }}
    AzureCLIImage: {{ .Values.AzureCLIImage | quote }}
    CaCert: {{ .Values.Certificates.Ca.Cert | quote }}
    FrontProxyCaCert: {{ .Values.Certificates.FrontProxyCa.Cert | quote }}
    ImageConfigFormat: {{ .Values.ImageConfigFormat | quote }}
    NodeImage: {{ .Values.NodeImage | quote }}
    OAuthProxyImage: {{ .Values.OAuthProxyImage | quote }}
    PrometheusAlertBufferImage: {{ .Values.PrometheusAlertBufferImage | quote }}
    PrometheusAlertManagerImage: {{ .Values.PrometheusAlertManagerImage | quote }}
    PrometheusImage: {{ .Values.PrometheusImage | quote }}
    PrometheusNodeExporterImage: {{ .Values.PrometheusNodeExporterImage | quote }}
    PrometheusProxySessionSecret: {{ .Values.PrometheusProxySessionSecret | quote }}
    RegistryConsoleImage: {{ .Values.RegistryConsoleImage | quote }}
    RegistryHTTPSecret: {{ .Values.RegistryHTTPSecret | quote }}
    RegistryImage: {{ .Values.RegistryImage | quote }}
    RegistryCert: {{ .Values.Certificates.Registry.Cert | quote }}
    RegistryKey: {{ .Values.Certificates.Registry.Key | quote }}
    RegistryStorageAccount: {{ .Values.RegistryStorageAccount | quote }}
    RegistryConsoleOAuthSecret: {{ .Values.RegistryConsoleOAuthSecret | quote }}
    RouterStatsPassword: {{ .Values.RouterStatsPassword | quote }}
    RouterImage: {{ .Values.RouterImage | quote }}
    RouterCert: {{ .Values.Certificates.Router.Cert | quote }}
    RouterKey: {{ .Values.Certificates.Router.Key | quote }}
    ServiceCatalogCaCert: {{ .Values.Certificates.ServiceCatalogCa.Cert | quote }}
    ServiceCatalogClusterID: {{ .Values.ServiceCatalogClusterID | quote }}
    ServiceCatalogImage: {{ .Values.ServiceCatalogImage | quote }}
    ServiceCatalogServerCert: {{ .Values.Certificates.ServiceCatalogServer.Cert | quote }}
    ServiceCatalogServerKey: {{ .Values.Certificates.ServiceCatalogServer.Key | quote }}
    ServiceSigningCaCert: {{ .Values.Certificates.ServiceSigningCa.Cert | quote }}
    TemplateServiceBrokerImage: {{ .Values.TemplateServiceBrokerImage | quote }}
    WebConsoleImage: {{ .Values.WebConsoleImage | quote }}

  manifest.yaml: |
    name: openshift
    location: {{ .Values.Location | quote }}
    properties:
      openShiftVersion: "v3.10"
      publicHostname: {{ .Values.PublicHostname | quote }}
      routingConfigSubdomain: {{ .Values.RoutingConfigSubdomain | quote }}
      agentPoolProfiles:
      - name: compute
        count: 1
        vmSize: Standard_D2s_v3
      - name: infra
        count: 1
        vmSize: Standard_D2s_v3
        role: infra
      servicePrincipalProfile:
        clientID: {{ .Values.ClientID | quote }}
        secret: {{ .Values.ClientSecret | quote }}
