apiVersion: v1
kind: Secret
metadata:
  name: sync
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
stringData:
  config.yaml: |
    AlertManagerProxySessionSecret: {{ .Values.AlertManagerProxySessionSecret | quote }}
    AlertsProxySessionSecret: {{ .Values.AlertsProxySessionSecret | quote }}
    AnsibleServiceBrokerImage: {{ .Values.AnsibleServiceBrokerImage | quote }}
    AzureCLIImage: {{ .Values.AzureCLIImage | quote }}
    CaCert: {{ .Values.CaCert | quote }}
    FrontProxyCaCert: {{ .Values.FrontProxyCaCert | quote }}
    NodeImage: {{ .Values.NodeImage | quote }}
    OAuthProxyImage: {{ .Values.OAuthProxyImage | quote }}
    PrometheusAlertBufferImage: {{ .Values.PrometheusAlertBufferImage | quote }}
    PrometheusAlertManagerImage: {{ .Values.PrometheusAlertManagerImage | quote }}
    PrometheusImage: {{ .Values.PrometheusImage | quote }}
    PrometheusNodeExporterImage: {{ .Values.PrometheusNodeExporterImage | quote }}
    PrometheusProxySessionSecret: {{ .Values.PrometheusProxySessionSecret | quote }}
    RegistryCert: {{ .Values.RegistryCert | quote }}
    RegistryConsoleImage: {{ .Values.RegistryConsoleImage | quote }}
    RegistryHTTPSecret: {{ .Values.RegistryHTTPSecret | quote }}
    RegistryImage: {{ .Values.RegistryImage | quote }}
    RegistryKey: {{ .Values.RegistryKey | quote }}
    RegistryStorageAccount: {{ .Values.RegistryStorageAccount | quote }}
    RouterCert: {{ .Values.RouterCert | quote }}
    RouterImage: {{ .Values.RouterImage | quote }}
    RouterKey: {{ .Values.RouterKey | quote }}
    ServiceCatalogCaCert: {{ .Values.ServiceCatalogCaCert | quote }}
    ServiceCatalogClusterID: {{ .Values.ServiceCatalogClusterID | quote }}
    ServiceCatalogImage: {{ .Values.ServiceCatalogImage | quote }}
    ServiceCatalogServerCert: {{ .Values.ServiceCatalogServerCert | quote }}
    ServiceCatalogServerKey: {{ .Values.ServiceCatalogServerKey | quote }}
    ServiceSigningCaCert: {{ .Values.ServiceSigningCaCert | quote }}
    TemplateServiceBrokerImage: {{ .Values.TemplateServiceBrokerImage | quote }}
    TunnelHostname: {{ .Values.TunnelHostname | quote }}
    TunnelImage: {{ .Values.TunnelImage | quote }}
    WebConsoleImage: {{ .Values.WebConsoleImage | quote }}

  manifest.yaml: |
    name: openshift
    location: {{ .Values.Location | quote }}
    properties:
      openShiftVersion: "3.10"
      publicHostname: {{ .Values.PublicHostname | quote }}
      routingConfigSubdomain: {{ .Values.RoutingConfigSubdomain | quote }}
      agentPoolProfiles:
      - name: compute
        count: 1
        vmSize: Standard_D2s_v3
      - name: infra
        count: 1
        vmSize: Standard_D2s_v3
        role: infra
      servicePrincipalProfile:
        clientID: {{ .Values.ClientID | quote }}
        secret: {{ .Values.ClientSecret | quote }}
