apiVersion: v1
kind: Secret
metadata:
  name: tunnel
data:
  ca.crt: {{ .Values.CaCert }}
  tunnel.crt: {{ .Values.TunnelCert }}
  tunnel.key: {{ .Values.TunnelKey }}
stringData:
  tunnel.conf: |
    mode: server
    address: 0.0.0.0:444
    interface: tunnel
    keyPath: /etc/tunnel/tunnel.key
    certPath: /etc/tunnel/tunnel.crt
    caCertPath: /etc/tunnel/ca.crt
    clientOrganization: system:nodes
    advertiseCIDRs:
    - eth0/32
