apiVersion: v1
kind: Secret
metadata:
  name: tunnel
stringData:
  tunnel.conf: |
    mode: server
    address: 0.0.0.0:444
    interface: tunnel
    keyPath: /etc/origin/master/master.server.key
    certPath: /etc/origin/master/master.server.crt
    caCertPath: /etc/origin/master/ca.crt
    clientOrganization: system:nodes
    advertiseCIDRs:
    - eth0/32
