apiVersion: v1
kind: Secret
metadata:
  name: tunnel
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
data:
  ca.crt: {{ .Values.CaCert | quote }}
  tunnel.crt: {{ .Values.TunnelCert | quote }}
  tunnel.key: {{ .Values.TunnelKey | quote }}
stringData:
  tunnel.conf: |
    mode: server
    address: 0.0.0.0:444
    interface: tunnel
    keyPath: /etc/tunnel/tunnel.key
    certPath: /etc/tunnel/tunnel.crt
    caCertPath: /etc/tunnel/ca.crt
    clientOrganization: system:nodes
    advertiseCIDRs:
    - eth0/32
