apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-api
spec:
  replicas: 1
  selector:
    matchLabels:
      openshift.io/component: api
  template:
    metadata:
      annotations:
        checksum/secret-etc-origin-master: {{ include (print $.Template.BasePath "/Secret/etc-origin-master.yaml") . | sha256sum | quote }}
        checksum/secret-etc-origin-cloudprovider: {{ include (print $.Template.BasePath "/Secret/etc-origin-cloudprovider.yaml") . | sha256sum | quote }}
      labels:
        openshift.io/component: api
    spec:
      containers:
      - name: api
        image: {{ .Values.ControlPlaneImage | quote }}
        imagePullPolicy: Always
        command:
        - /bin/bash
        - -c
        args:
        - |
          set -euo pipefail
          if [[ -f /etc/origin/master/master.env ]]; then
            set -o allexport
            source /etc/origin/master/master.env
          fi
          exec openshift start master api --config=/etc/origin/master/master-config.yaml --loglevel=${DEBUG_LOGLEVEL:-2}
        env:
        - name: DEBUG_LOGLEVEL
          value: "4"
        # TODO: need to re-enable these
        #livenessProbe:
        #  httpGet:
        #    path: healthz
        #    port: 443
        #    scheme: HTTPS
        #  initialDelaySeconds: 45
        #  timeoutSeconds: 10
        #readinessProbe:
        #  httpGet:
        #    path: healthz/ready
        #    port: 443
        #    scheme: HTTPS
        #  initialDelaySeconds: 10
        #  timeoutSeconds: 10
        volumeMounts:
        - name: master-config
          mountPath: /etc/origin/master/
          readOnly: true
        - name: master-cloud-provider
          mountPath: /etc/origin/cloudprovider/
          readOnly: true
      volumes:
      - name: master-config
        secret:
          secretName: etc-origin-master
      - name: master-cloud-provider
        secret:
          secretName: etc-origin-cloudprovider
