apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-etcd
  annotations:
    checksum/etc-etcd: {{ include (print $.Template.BasePath "/Secret/etc-etcd.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      openshift.io/component: etcd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        openshift.io/component: etcd
    spec:
      containers:
      - name: etcd
        image: {{ .Values.MasterEtcdImage }}
        imagePullPolicy: Always
        workingDir: /var/lib/etcd
        command:
        - /bin/sh
        - -c
        args:
        - |
          set -o allexport
          source /etc/etcd/etcd.conf
          exec etcd
        livenessProbe:
          exec:
            command:
            - etcdctl
            - --ca-file
            - /etc/etcd/ca.crt
            - --cert-file
            - /etc/etcd/peer.crt
            - --key-file
            - /etc/etcd/peer.key
            - --endpoints
            - https://master-etcd:2379
            - cluster-health
          initialDelaySeconds: 45
        volumeMounts:
        - name: master-config
          mountPath: /etc/etcd/
          readOnly: true
        - name: master-data
          mountPath: /var/lib/etcd/
      volumes:
      - name: master-config
        secret:
          secretName: etc-etcd
      - name: master-data
        emptyDir: # TODO: BIG FAT WARNING, CHANGE THIS BEFORE PRODUCTION :)
