{{if 0}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync
  annotations:
    checksum/sync: {{ include (print $.Template.BasePath "/Secret/sync.yaml") . | sha256sum }}
    checksum/admin-kubeconfig: {{ include (print $.Template.BasePath "/Secret/admin-kubeconfig.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sync
  template:
    metadata:
      labels:
        app: sync
    spec:
      automountServiceAccountToken: false
      containers:
      - name: sync
        image: {{ .Values.SyncImage }}
        imagePullPolicy: Always
        env:
        - name: KUBECONFIG
          value: /tmp/kubeconfig/admin.kubeconfig
        volumeMounts:
        - name: config
          mountPath: /_data
          readOnly: true
        - name: kubeconfig
          mountPath: /tmp/kubeconfig
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: sync
      - name: kubeconfig
        secret:
          secretName: admin-kubeconfig
{{end}}
