apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-origin-master
data:
  scheduler.json: |
    {
      "apiVersion": "v1",
      "kind": "Policy",
      "predicates": [
        {
          "name": "NoVolumeZoneConflict"
        },
        {
          "name": "MaxEBSVolumeCount"
        },
        {
          "name": "MaxGCEPDVolumeCount"
        },
        {
          "name": "MaxAzureDiskVolumeCount"
        },
        {
          "name": "MatchInterPodAffinity"
        },
        {
          "name": "NoDiskConflict"
        },
        {
          "name": "GeneralPredicates"
        },
        {
          "name": "PodToleratesNodeTaints"
        },
        {
          "name": "CheckNodeMemoryPressure"
        },
        {
          "name": "CheckNodeDiskPressure"
        },
        {
          "name": "CheckVolumeBinding"
        },
        {
          "argument": {
            "serviceAffinity": {
              "labels": [
                "region"
              ]
            }
          },
          "name": "Region"
        }
      ],
      "priorities": [
        {
          "name": "SelectorSpreadPriority",
          "weight": 1
        },
        {
          "name": "InterPodAffinityPriority",
          "weight": 1
        },
        {
          "name": "LeastRequestedPriority",
          "weight": 1
        },
        {
          "name": "BalancedResourceAllocation",
          "weight": 1
        },
        {
          "name": "NodePreferAvoidPodsPriority",
          "weight": 10000
        },
        {
          "name": "NodeAffinityPriority",
          "weight": 1
        },
        {
          "name": "TaintTolerationPriority",
          "weight": 1
        },
        {
          "argument": {
            "serviceAntiAffinity": {
              "label": "zone"
            }
          },
          "name": "Zone",
          "weight": 2
        }
      ]
    }

  master.etcd-ca.crt: |
{{ .Values.etcdCaCert | b64dec | indent 4 }}

  ca.crt: |
{{ .Values.caCert | b64dec | indent 4 }}

  front-proxy-ca.crt: |
{{ .Values.frontProxyCaCert | b64dec | indent 4 }}

  service-signer.crt: |
{{ .Values.serviceServingCaCert | b64dec | indent 4 }}

  master.etcd-client.crt: |
{{ .Values.etcdClientCert | b64dec | indent 4 }}

  aggregator-front-proxy.crt: |
{{ .Values.aggregatorFrontProxyCert | b64dec | indent 4 }}

  master.kubelet-client.crt: |
{{ .Values.masterKubeletClientCert | b64dec | indent 4 }}

  master.proxy-client.crt: |
{{ .Values.masterProxyClientCert | b64dec | indent 4 }}

  master.server.crt: |
{{ .Values.masterServerCert | b64dec | indent 4 }}

  serviceaccounts.public.key: |
{{ .Values.serviceAccountPublicKey | b64dec | indent 4 }}
