# TODO: roll all the configmaps into their corresponding secrets?
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-etcd
data:
  etcd.conf: |
    ETCD_ADVERTISE_CLIENT_URLS=https://master-etcd:2379
    ETCD_CERT_FILE=/etc/etcd/server.crt
    ETCD_CLIENT_CERT_AUTH="true"
    ETCD_DATA_DIR=/var/lib/etcd/
    ETCD_ELECTION_TIMEOUT=2500
    ETCD_HEARTBEAT_INTERVAL=500
    ETCD_INITIAL_ADVERTISE_PEER_URLS=https://master-etcd:2380
    ETCD_INITIAL_CLUSTER=default=https://master-etcd:2380
    ETCD_KEY_FILE=/etc/etcd/server.key
    ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
    ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
    ETCD_PEER_CERT_FILE=/etc/etcd/peer.crt
    ETCD_PEER_CLIENT_CERT_AUTH="true"
    ETCD_PEER_KEY_FILE=/etc/etcd/peer.key
    ETCD_PEER_TRUSTED_CA_FILE=/etc/etcd/ca.crt
    ETCD_QUOTA_BACKEND_BYTES=4294967296
    ETCD_TRUSTED_CA_FILE=/etc/etcd/ca.crt

  ca.crt: |
{{ .Values.etcdCaCert | b64dec | indent 4 }}

  server.crt: |
{{ .Values.etcdServerCert | b64dec | indent 4 }}

  peer.crt: |
{{ .Values.etcdPeerCert | b64dec | indent 4 }}
