kind: Deployment
apiVersion: apps/v1
metadata:
  name: master-api
spec:
  replicas: 1
  selector:
    matchLabels:
      openshift.io/component: api
  template:
    metadata:
      labels:
        openshift.io/component: api
    spec:
      containers:
      - name: api
        image: docker.io/openshift/origin-control-plane:v3.10
        command:
        - /bin/bash
        - -c
        args:
        - |
          set -euo pipefail
          if [[ -f /etc/origin/master/master.env ]]; then
            set -o allexport
            source /etc/origin/master/master.env
          fi
          exec openshift start master api --config=/etc/origin/master/master-config.yaml --loglevel=${DEBUG_LOGLEVEL:-2}
        env:
        - name: DEBUG_LOGLEVEL
          value: "4"
        livenessProbe:
          httpGet:
            path: healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 45
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: healthz/ready
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 10
          timeoutSeconds: 10
        volumeMounts:
        - name: master-config
          mountPath: /etc/origin/master/
          readOnly: true
        - name: master-cloud-provider
          mountPath: /etc/origin/cloudprovider/
          readOnly: true
        - name: master-data
          mountPath: /var/lib/origin/
      volumes:
      - name: master-config
        projected:
          sources:
          - secret:
              name: master-certs
          - configMap:
              name: etc-origin-master
      - name: master-cloud-provider
        configMap:
          name: etc-origin-cloudprovider
      - name: master-data
        emptyDir:  ### BIG FAT WARNING, CHANGE THIS BEFORE PRODUCTION :)
