apiVersion: apps/v1
kind: Deployment
metadata:
  name: import
spec:
  replicas: 1
  selector:
    matchLabels:
      app: import
  template:
    metadata:
      labels:
        app: import
    spec:
      containers:
      - name: import
        image: {{ .Values.importImage }}
        imagePullPolicy: Always
        env:
        - name: KUBECONFIG
          value: /tmp/kubeconfig/admin.kubeconfig
        volumeMounts:
        - name: config
          mountPath: /tmp/config
          readOnly: true
        - name: kubeconfig
          mountPath: /tmp/kubeconfig
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: import
      - name: kubeconfig
        secret:
          secretName: admin-kubeconfig # TODO: need to use a less powerful token
